import { getContainer } from '@src/services/azure/CosmosService';
import { IUser } from '@src/models/User';
import logger from 'jet-logger';

const CONTAINER_NAMES = {
  USERS: 'Users',
  FILES: 'Files',
  SHARE_LINKS: 'ShareLinks',
};

/**
 * Create a new user
 */
export const createUser = async (user: IUser): Promise<IUser> => {
  try {
    const container = await getContainer(CONTAINER_NAMES.USERS, '/userId');
    const { resource } = await container.items.create(user);

    if (!resource) {
      throw new Error('Failed to create user');
    }

    return resource as IUser;
  } catch (error: any) {
    if (error.code === 409) {
      throw new Error('User with this email already exists');
    }
    logger.err(error);
    throw new Error('Failed to create user');
  }
};

/**
 * Get user by userId
 */
export const getUserById = async (userId: string): Promise<IUser | null> => {
  try {
    const container = await getContainer(CONTAINER_NAMES.USERS, '/userId');
    // Query by userId (partition key) instead of using item(id, partitionKey)
    // because Cosmos DB auto-generates an 'id' field that differs from userId
    const querySpec = {
      query: 'SELECT * FROM c WHERE c.userId = @userId',
      parameters: [
        {
          name: '@userId',
          value: userId,
        },
      ],
    };

    const { resources } = await container.items.query<IUser>(querySpec).fetchAll();
    return resources.length > 0 ? resources[0] : null;
  } catch (error: any) {
    if (error.code === 404) {
      return null;
    }
    logger.err(error);
    throw new Error('Failed to get user');
  }
};

/**
 * Get user by email
 */
export const getUserByEmail = async (email: string): Promise<IUser | null> => {
  try {
    const container = await getContainer(CONTAINER_NAMES.USERS, '/userId');
    const querySpec = {
      query: 'SELECT * FROM c WHERE c.email = @email',
      parameters: [
        {
          name: '@email',
          value: email,
        },
      ],
    };

    const { resources } = await container.items
      .query<IUser>(querySpec)
      .fetchAll();

    return resources.length > 0 ? resources[0] : null;
  } catch (error: any) {
    // If it's a 404 or not found error, return null (user doesn't exist)
    if (error.code === 404) {
      return null;
    }
    // Log the error but don't throw - allow caller to handle
    logger.err('Error getting user by email:', error);
    // Return null instead of throwing - this allows registration to proceed
    // if the check fails due to connection issues
    return null;
  }
};

/**
 * Update user
 */
export const updateUser = async (user: IUser): Promise<IUser> => {
  try {
    const container = await getContainer(CONTAINER_NAMES.USERS, '/userId');
    // First, get the user to find the Cosmos DB 'id' field
    const existingUser = await getUserById(user.userId);
    if (!existingUser) {
      throw new Error('User not found');
    }

    // Use the Cosmos DB 'id' field for the replace operation
    // The 'id' field is auto-generated by Cosmos DB and is different from userId
    const cosmosId = (existingUser as any).id || user.userId;
    const { resource } = await container
      .item(cosmosId, user.userId)
      .replace(user);

    if (!resource) {
      throw new Error('Failed to update user');
    }

    return resource as IUser;
  } catch (error: any) {
    logger.err(error);
    throw new Error('Failed to update user');
  }
};

/**
 * Update last login timestamp
 */
export const updateLastLogin = async (userId: string): Promise<void> => {
  try {
    const user = await getUserById(userId);
    if (!user) {
      throw new Error('User not found');
    }

    user.lastLogin = new Date();
    await updateUser(user);
  } catch (error) {
    logger.err(error);
    throw new Error('Failed to update last login');
  }
};
 

export default {
  createUser,
  getUserById,
  getUserByEmail,
  updateUser,
  updateLastLogin,
};
